/**
 * Meta-relevant Pokemon for each open league, sourced from PvPoke rankings.
 * Shadow forms share an entry with their base form (the "Shadow " prefix
 * is handled separately by TeamInput).
 */

export const GREAT_LEAGUE_POKEMON: string[] = [
  "Abomasnow",
  "Absol",
  "Accelgor",
  "Aegislash Shield",
  "Aerodactyl",
  "Aggron",
  "Aipom",
  "Alakazam",
  "Alomomola",
  "Altaria",
  "Amaura",
  "Ambipom",
  "Amoonguss",
  "Ampharos",
  "Annihilape",
  "Anorith",
  "Appletun",
  "Araquanid",
  "Arbok",
  "Arboliva",
  "Arcanine",
  "Arcanine Hisui",
  "Archen",
  "Archeops",
  "Arctibax",
  "Ariados",
  "Armaldo",
  "Armarouge",
  "Aromatisse",
  "Aron",
  "Articuno",
  "Articuno Galar",
  "Audino",
  "Aurorus",
  "Avalugg",
  "Avalugg Hisui",
  "Axew",
  "Azelf",
  "Azumarill",
  "Banette",
  "Barbaracle",
  "Basculin Red Striped",
  "Bastiodon",
  "Baxcalibur",
  "Bayleef",
  "Beartic",
  "Beautifly",
  "Beedrill",
  "Beheeyem",
  "Bellibolt",
  "Bellossom",
  "Bergmite",
  "Bewear",
  "Bibarel",
  "Bisharp",
  "Blacephalon",
  "Blastoise",
  "Blaziken",
  "Blissey",
  "Boldore",
  "Boltund",
  "Bombirdier",
  "Bonsly",
  "Bouffalant",
  "Braixen",
  "Braviary",
  "Braviary Hisui",
  "Breloom",
  "Brionne",
  "Bronzong",
  "Bruxish",
  "Bulbasaur",
  "Buneary",
  "Butterfree",
  "Buzzwole",
  "Cacturne",
  "Camerupt",
  "Carbink",
  "Carkol",
  "Carnivine",
  "Carracosta",
  "Castform",
  "Castform Rainy",
  "Castform Snowy",
  "Castform Sunny",
  "Celebi",
  "Celesteela",
  "Centiskorch",
  "Ceruledge",
  "Cetitan",
  "Cetoddle",
  "Chandelure",
  "Chansey",
  "Charizard",
  "Charjabug",
  "Charmeleon",
  "Chatot",
  "Cherrim",
  "Chesnaught",
  "Chespin",
  "Chimecho",
  "Chinchou",
  "Cinccino",
  "Cinderace",
  "Clamperl",
  "Clauncher",
  "Clawitzer",
  "Claydol",
  "Clefable",
  "Clefairy",
  "Clobbopus",
  "Clodsire",
  "Cloyster",
  "Coalossal",
  "Cofagrigus",
  "Combusken",
  "Comfey",
  "Conkeldurr",
  "Corphish",
  "Corsola",
  "Corsola Galar",
  "Corviknight",
  "Corvisquire",
  "Crabominable",
  "Crabrawler",
  "Cradily",
  "Cranidos",
  "Crawdaunt",
  "Cresselia",
  "Crobat",
  "Crocalor",
  "Croconaw",
  "Crustle",
  "Cryogonal",
  "Cubone",
  "Cursola",
  "Dachsbun",
  "Darmanitan Galar Standard",
  "Darmanitan Standard",
  "Dartrix",
  "Darumaka",
  "Darumaka Galar",
  "Decidueye",
  "Decidueye Hisui",
  "Dedenne",
  "Deerling",
  "Delcatty",
  "Delphox",
  "Deoxys Defense",
  "Deoxys Speed",
  "Dewgong",
  "Dewott",
  "Dhelmise",
  "Dialga",
  "Diancie",
  "Diggersby",
  "Dipplin",
  "Dodrio",
  "Dolliv",
  "Dondozo",
  "Donphan",
  "Dottler",
  "Doublade",
  "Dragalge",
  "Dragapult",
  "Dragonair",
  "Dragonite",
  "Drakloak",
  "Drampa",
  "Drapion",
  "Drifblim",
  "Drifloon",
  "Drilbur",
  "Drizzile",
  "Drowzee",
  "Druddigon",
  "Dubwool",
  "Dudunsparce Two Segment",
  "Dugtrio",
  "Dugtrio Alola",
  "Dunsparce",
  "Duosion",
  "Duraludon",
  "Durant",
  "Dusclops",
  "Dusknoir",
  "Dustox",
  "Dwebble",
  "Eelektrik",
  "Eelektross",
  "Eevee",
  "Eldegoss",
  "Electabuzz",
  "Electivire",
  "Electrode",
  "Electrode Hisui",
  "Elekid",
  "Elgyem",
  "Emboar",
  "Emolga",
  "Empoleon",
  "Entei",
  "Escavalier",
  "Espeon",
  "Espurr",
  "Excadrill",
  "Exeggcute",
  "Exeggutor",
  "Exeggutor Alola",
  "Exploud",
  "Falinks",
  "Farfetchd",
  "Farfetchd Galar",
  "Fearow",
  "Feraligatr",
  "Ferroseed",
  "Ferrothorn",
  "Flaaffy",
  "Flabebe",
  "Flamigo",
  "Flapple",
  "Flareon",
  "Fletchinder",
  "Floatzel",
  "Floette",
  "Floragato",
  "Florges",
  "Flygon",
  "Forretress",
  "Fraxure",
  "Frigibax",
  "Frillish Male",
  "Frogadier",
  "Froslass",
  "Frosmoth",
  "Fuecoco",
  "Furfrou",
  "Furret",
  "Gabite",
  "Gallade",
  "Galvantula",
  "Garbodor",
  "Garchomp",
  "Gardevoir",
  "Garganacl",
  "Gastrodon",
  "Genesect",
  "Gengar",
  "Geodude",
  "Geodude Alola",
  "Gholdengo",
  "Gigalith",
  "Girafarig",
  "Giratina Altered",
  "Giratina Origin",
  "Glaceon",
  "Glalie",
  "Gligar",
  "Glimmet",
  "Glimmora",
  "Gliscor",
  "Gloom",
  "Gogoat",
  "Golbat",
  "Goldeen",
  "Golduck",
  "Golem",
  "Golem Alola",
  "Golett",
  "Golisopod",
  "Golurk",
  "Goodra",
  "Gorebyss",
  "Gothitelle",
  "Gothorita",
  "Gourgeist Average",
  "Gourgeist Large",
  "Gourgeist Small",
  "Gourgeist Super",
  "Grafaiai",
  "Granbull",
  "Grapploct",
  "Graveler",
  "Graveler Alola",
  "Greedent",
  "Greninja",
  "Grimer",
  "Grimer Alola",
  "Grimmsnarl",
  "Grotle",
  "Groudon",
  "Grovyle",
  "Growlithe",
  "Growlithe Hisui",
  "Grumpig",
  "Gumshoos",
  "Gurdurr",
  "Guzzlord",
  "Gyarados",
  "Hakamo O",
  "Hariyama",
  "Hatterene",
  "Hattrem",
  "Haunter",
  "Hawlucha",
  "Haxorus",
  "Heatmor",
  "Heatran",
  "Heliolisk",
  "Heracross",
  "Herdier",
  "Hippopotas",
  "Hippowdon",
  "Hitmonchan",
  "Hitmonlee",
  "Hitmontop",
  "Ho Oh",
  "Honchkrow",
  "Honedge",
  "Hoopa",
  "Houndoom",
  "Houndour",
  "Houndstone",
  "Huntail",
  "Hydrapple",
  "Hydreigon",
  "Hypno",
  "Illumise",
  "Incineroar",
  "Indeedee Female",
  "Indeedee Male",
  "Infernape",
  "Inteleon",
  "Ivysaur",
  "Jellicent Male",
  "Jirachi",
  "Jolteon",
  "Jumpluff",
  "Jynx",
  "Kabuto",
  "Kabutops",
  "Kadabra",
  "Kangaskhan",
  "Karrablast",
  "Kartana",
  "Kecleon",
  "Kilowattrel",
  "Kingambit",
  "Kingdra",
  "Kingler",
  "Klang",
  "Klawf",
  "Kleavor",
  "Klefki",
  "Klinklang",
  "Koffing",
  "Komala",
  "Kommo O",
  "Krabby",
  "Kricketune",
  "Krokorok",
  "Krookodile",
  "Kubfu",
  "Kyogre",
  "Lairon",
  "Lampent",
  "Landorus Incarnate",
  "Lanturn",
  "Lapras",
  "Larvesta",
  "Latias",
  "Latios",
  "Leafeon",
  "Leavanny",
  "Ledian",
  "Lickilicky",
  "Lickitung",
  "Liepard",
  "Lileep",
  "Lilligant",
  "Lilligant Hisui",
  "Linoone",
  "Linoone Galar",
  "Litleo",
  "Lokix",
  "Lombre",
  "Lopunny",
  "Loudred",
  "Lucario",
  "Ludicolo",
  "Lugia",
  "Lumineon",
  "Lunatone",
  "Lurantis",
  "Luxio",
  "Luxray",
  "Lycanroc Dusk",
  "Lycanroc Midday",
  "Lycanroc Midnight",
  "Machamp",
  "Machoke",
  "Machop",
  "Magby",
  "Magcargo",
  "Magmar",
  "Magmortar",
  "Magnemite",
  "Magneton",
  "Magnezone",
  "Malamar",
  "Mamoswine",
  "Mandibuzz",
  "Manectric",
  "Mankey",
  "Mantine",
  "Mantyke",
  "Maractus",
  "Marowak",
  "Marowak Alola",
  "Marshtomp",
  "Masquerain",
  "Maushold Family Of Four",
  "Mawile",
  "Medicham",
  "Meganium",
  "Melmetal",
  "Meltan",
  "Meowscarada",
  "Meowstic Female",
  "Meowstic Male",
  "Mesprit",
  "Metagross",
  "Metang",
  "Mew",
  "Mewtwo",
  "Mienfoo",
  "Mienshao",
  "Mightyena",
  "Milotic",
  "Miltank",
  "Minun",
  "Misdreavus",
  "Mismagius",
  "Moltres",
  "Moltres Galar",
  "Monferno",
  "Morgrem",
  "Morpeko Full Belly",
  "Mothim",
  "Mr Mime",
  "Mr Mime Galar",
  "Mr Rime",
  "Mudbray",
  "Mudsdale",
  "Muk",
  "Muk Alola",
  "Munchlax",
  "Munna",
  "Murkrow",
  "Musharna",
  "Naclstack",
  "Naganadel",
  "Nidoking",
  "Nidoqueen",
  "Nidorina",
  "Nidorino",
  "Ninetales",
  "Ninetales Alola",
  "Ninjask",
  "Noctowl",
  "Noivern",
  "Nosepass",
  "Nuzleaf",
  "Obstagoon",
  "Octillery",
  "Oddish",
  "Oinkologne Female",
  "Oinkologne Male",
  "Omanyte",
  "Omastar",
  "Onix",
  "Oranguru",
  "Orbeetle",
  "Oricorio Baile",
  "Oricorio Pau",
  "Oricorio Pom Pom",
  "Oricorio Sensu",
  "Overqwil",
  "Pachirisu",
  "Palkia",
  "Palossand",
  "Palpitoad",
  "Pancham",
  "Pangoro",
  "Parasect",
  "Passimian",
  "Pawmo",
  "Pawmot",
  "Pawniard",
  "Pelipper",
  "Perrserker",
  "Persian",
  "Persian Alola",
  "Phanpy",
  "Pidgeot",
  "Pidgeotto",
  "Pignite",
  "Piloswine",
  "Pineco",
  "Pinsir",
  "Piplup",
  "Plusle",
  "Poipole",
  "Politoed",
  "Poliwhirl",
  "Poliwrath",
  "Polteageist",
  "Ponyta",
  "Ponyta Galar",
  "Popplio",
  "Porygon",
  "Porygon Z",
  "Porygon2",
  "Primarina",
  "Primeape",
  "Prinplup",
  "Probopass",
  "Pumpkaboo Average",
  "Pumpkaboo Large",
  "Pumpkaboo Small",
  "Pumpkaboo Super",
  "Pupitar",
  "Purugly",
  "Pyroar Male",
  "Quagsire",
  "Quaquaval",
  "Quaxwell",
  "Quilava",
  "Quilladin",
  "Qwilfish",
  "Qwilfish Hisui",
  "Raboot",
  "Raichu",
  "Raichu Alola",
  "Raikou",
  "Rampardos",
  "Rapidash",
  "Rapidash Galar",
  "Raticate",
  "Raticate Alola",
  "Rayquaza",
  "Regice",
  "Regidrago",
  "Regieleki",
  "Regigigas",
  "Regirock",
  "Registeel",
  "Relicanth",
  "Reuniclus",
  "Revavroom",
  "Rhydon",
  "Rhyhorn",
  "Rhyperior",
  "Ribombee",
  "Rillaboom",
  "Roggenrola",
  "Roselia",
  "Roserade",
  "Rotom",
  "Rotom Fan",
  "Rotom Frost",
  "Rotom Heat",
  "Rotom Mow",
  "Rotom Wash",
  "Rowlet",
  "Rufflet",
  "Runerigus",
  "Sableye",
  "Salamence",
  "Salazzle",
  "Samurott",
  "Samurott Hisui",
  "Sandshrew",
  "Sandshrew Alola",
  "Sandslash",
  "Sandslash Alola",
  "Sandygast",
  "Sawk",
  "Sawsbuck",
  "Sceptile",
  "Scizor",
  "Scolipede",
  "Scrafty",
  "Scraggy",
  "Scyther",
  "Seadra",
  "Seaking",
  "Sealeo",
  "Seel",
  "Seismitoad",
  "Serperior",
  "Servine",
  "Seviper",
  "Sharpedo",
  "Shaymin Land",
  "Shaymin Sky",
  "Shelgon",
  "Shellos",
  "Shiftry",
  "Shiinotic",
  "Sigilyph",
  "Simipour",
  "Simisage",
  "Simisear",
  "Sirfetchd",
  "Skarmory",
  "Skeledirge",
  "Skiddo",
  "Skorupi",
  "Skrelp",
  "Skuntank",
  "Slaking",
  "Sliggoo",
  "Slowbro",
  "Slowbro Galar",
  "Slowking",
  "Slowking Galar",
  "Slowpoke",
  "Slowpoke Galar",
  "Slurpuff",
  "Smoochum",
  "Sneasel",
  "Sneasel Hisui",
  "Sneasler",
  "Snorlax",
  "Snover",
  "Snubbull",
  "Solosis",
  "Solrock",
  "Spidops",
  "Spinda",
  "Spiritomb",
  "Spoink",
  "Spritzee",
  "Stakataka",
  "Stantler",
  "Staraptor",
  "Staravia",
  "Starmie",
  "Steelix",
  "Stonjourner",
  "Stoutland",
  "Stufful",
  "Stunfisk",
  "Stunfisk Galar",
  "Stunky",
  "Sudowoodo",
  "Suicune",
  "Sunflora",
  "Swadloon",
  "Swalot",
  "Swampert",
  "Swanna",
  "Swellow",
  "Swirlix",
  "Swoobat",
  "Sylveon",
  "Talonflame",
  "Tangela",
  "Tangrowth",
  "Tapu Fini",
  "Tatsugiri Curly",
  "Tatsugiri Droopy",
  "Tatsugiri Stretchy",
  "Tauros",
  "Tauros Paldea Aqua Breed",
  "Tauros Paldea Blaze Breed",
  "Tauros Paldea Combat Breed",
  "Teddiursa",
  "Tentacool",
  "Tentacruel",
  "Thievul",
  "Throh",
  "Thundurus Incarnate",
  "Thwackey",
  "Timburr",
  "Tinkaton",
  "Tinkatuff",
  "Tirtouga",
  "Toedscool",
  "Toedscruel",
  "Togedemaru",
  "Togekiss",
  "Togetic",
  "Torkoal",
  "Tornadus Incarnate",
  "Torracat",
  "Torterra",
  "Totodile",
  "Toucannon",
  "Toxapex",
  "Toxicroak",
  "Toxtricity Amped",
  "Tranquill",
  "Trapinch",
  "Trevenant",
  "Tropius",
  "Trumbeak",
  "Tsareena",
  "Turtonator",
  "Turtwig",
  "Typhlosion",
  "Typhlosion Hisui",
  "Tyranitar",
  "Tyrantrum",
  "Tyrunt",
  "Umbreon",
  "Unfezant",
  "Unown",
  "Ursaluna",
  "Ursaring",
  "Urshifu Rapid Strike",
  "Urshifu Single Strike",
  "Uxie",
  "Vanillish",
  "Vanilluxe",
  "Vaporeon",
  "Varoom",
  "Venomoth",
  "Venusaur",
  "Vespiquen",
  "Vibrava",
  "Victini",
  "Victreebel",
  "Vigoroth",
  "Vikavolt",
  "Vileplume",
  "Vivillon",
  "Volbeat",
  "Volcanion",
  "Vullaby",
  "Wailmer",
  "Wailord",
  "Walrein",
  "Wartortle",
  "Watchog",
  "Weavile",
  "Weepinbell",
  "Weezing",
  "Weezing Galar",
  "Whimsicott",
  "Whirlipede",
  "Whiscash",
  "Wigglytuff",
  "Wobbuffet",
  "Wormadam Plant",
  "Wormadam Sandy",
  "Wormadam Trash",
  "Wugtrio",
  "Wyrdeer",
  "Xatu",
  "Yanma",
  "Yanmega",
  "Zangoose",
  "Zapdos",
  "Zapdos Galar",
  "Zebstrika",
  "Zoroark",
  "Zoroark Hisui",
  "Zweilous",
  "Zygarde 10",
  "Zygarde 50",
];

export const ULTRA_LEAGUE_POKEMON: string[] = [
  "Abomasnow",
  "Absol",
  "Accelgor",
  "Aegislash Shield",
  "Aerodactyl",
  "Aggron",
  "Alakazam",
  "Alomomola",
  "Altaria",
  "Ambipom",
  "Amoonguss",
  "Ampharos",
  "Annihilape",
  "Appletun",
  "Araquanid",
  "Arbok",
  "Arboliva",
  "Arcanine",
  "Arcanine Hisui",
  "Archeops",
  "Arctibax",
  "Armaldo",
  "Armarouge",
  "Aromatisse",
  "Articuno",
  "Articuno Galar",
  "Audino",
  "Aurorus",
  "Avalugg",
  "Avalugg Hisui",
  "Azelf",
  "Azumarill",
  "Banette",
  "Barbaracle",
  "Basculin Red Striped",
  "Bastiodon",
  "Baxcalibur",
  "Beartic",
  "Beedrill",
  "Beheeyem",
  "Bellibolt",
  "Bellossom",
  "Bewear",
  "Bibarel",
  "Bisharp",
  "Blacephalon",
  "Blastoise",
  "Blaziken",
  "Blissey",
  "Boldore",
  "Boltund",
  "Bombirdier",
  "Bouffalant",
  "Braviary",
  "Braviary Hisui",
  "Breloom",
  "Brionne",
  "Bronzong",
  "Bruxish",
  "Buzzwole",
  "Cacturne",
  "Camerupt",
  "Carbink",
  "Carnivine",
  "Carracosta",
  "Celebi",
  "Celesteela",
  "Centiskorch",
  "Ceruledge",
  "Cetitan",
  "Chandelure",
  "Chansey",
  "Charizard",
  "Cherrim",
  "Chesnaught",
  "Chimecho",
  "Cinccino",
  "Cinderace",
  "Clawitzer",
  "Claydol",
  "Clefable",
  "Clodsire",
  "Cloyster",
  "Coalossal",
  "Cobalion",
  "Cofagrigus",
  "Comfey",
  "Conkeldurr",
  "Corviknight",
  "Crabominable",
  "Cradily",
  "Crawdaunt",
  "Cresselia",
  "Crobat",
  "Crocalor",
  "Crustle",
  "Cryogonal",
  "Cursola",
  "Dachsbun",
  "Darkrai",
  "Darmanitan Galar Standard",
  "Darmanitan Standard",
  "Dartrix",
  "Decidueye",
  "Decidueye Hisui",
  "Dedenne",
  "Delphox",
  "Deoxys Defense",
  "Deoxys Speed",
  "Dewgong",
  "Dhelmise",
  "Dialga",
  "Dialga Origin",
  "Diancie",
  "Dipplin",
  "Dodrio",
  "Dondozo",
  "Donphan",
  "Doublade",
  "Dragalge",
  "Dragapult",
  "Dragonite",
  "Drampa",
  "Drapion",
  "Drifblim",
  "Druddigon",
  "Dubwool",
  "Dudunsparce Two Segment",
  "Dunsparce",
  "Duraludon",
  "Durant",
  "Dusknoir",
  "Eelektross",
  "Eldegoss",
  "Electabuzz",
  "Electivire",
  "Electrode",
  "Electrode Hisui",
  "Emboar",
  "Empoleon",
  "Enamorus Incarnate",
  "Enamorus Therian",
  "Entei",
  "Escavalier",
  "Espeon",
  "Eternatus",
  "Excadrill",
  "Exeggutor",
  "Exeggutor Alola",
  "Exploud",
  "Falinks",
  "Fearow",
  "Feraligatr",
  "Ferrothorn",
  "Flamigo",
  "Flapple",
  "Flareon",
  "Floatzel",
  "Florges",
  "Flygon",
  "Forretress",
  "Fraxure",
  "Froslass",
  "Frosmoth",
  "Furfrou",
  "Furret",
  "Gabite",
  "Gallade",
  "Galvantula",
  "Garbodor",
  "Garchomp",
  "Gardevoir",
  "Garganacl",
  "Gastrodon",
  "Genesect",
  "Gengar",
  "Gholdengo",
  "Gigalith",
  "Girafarig",
  "Giratina Altered",
  "Giratina Origin",
  "Glaceon",
  "Glalie",
  "Gligar",
  "Glimmora",
  "Gliscor",
  "Gogoat",
  "Golbat",
  "Golduck",
  "Golem",
  "Golem Alola",
  "Golisopod",
  "Golurk",
  "Goodra",
  "Gorebyss",
  "Gothitelle",
  "Gourgeist Average",
  "Gourgeist Large",
  "Gourgeist Small",
  "Gourgeist Super",
  "Grafaiai",
  "Granbull",
  "Grapploct",
  "Graveler",
  "Graveler Alola",
  "Greedent",
  "Greninja",
  "Grimmsnarl",
  "Grotle",
  "Groudon",
  "Grumpig",
  "Gumshoos",
  "Gurdurr",
  "Guzzlord",
  "Gyarados",
  "Hariyama",
  "Hatterene",
  "Hawlucha",
  "Haxorus",
  "Heatmor",
  "Heatran",
  "Heliolisk",
  "Heracross",
  "Hippowdon",
  "Hitmonchan",
  "Hitmonlee",
  "Hitmontop",
  "Ho Oh",
  "Honchkrow",
  "Hoopa",
  "Hoopa Unbound",
  "Houndoom",
  "Houndstone",
  "Huntail",
  "Hydrapple",
  "Hydreigon",
  "Hypno",
  "Illumise",
  "Incineroar",
  "Indeedee Female",
  "Indeedee Male",
  "Infernape",
  "Inteleon",
  "Jellicent Male",
  "Jirachi",
  "Jolteon",
  "Jumpluff",
  "Jynx",
  "Kabutops",
  "Kangaskhan",
  "Kartana",
  "Kecleon",
  "Keldeo Ordinary",
  "Keldeo Resolute",
  "Kilowattrel",
  "Kingambit",
  "Kingdra",
  "Kingler",
  "Klang",
  "Klawf",
  "Kleavor",
  "Klefki",
  "Klinklang",
  "Komala",
  "Kommo O",
  "Krookodile",
  "Kyogre",
  "Kyurem",
  "Kyurem Black",
  "Kyurem White",
  "Lairon",
  "Landorus Incarnate",
  "Landorus Therian",
  "Lanturn",
  "Lapras",
  "Latias",
  "Latios",
  "Leafeon",
  "Leavanny",
  "Lickilicky",
  "Lilligant",
  "Lilligant Hisui",
  "Lokix",
  "Lopunny",
  "Lucario",
  "Ludicolo",
  "Lugia",
  "Lumineon",
  "Lunala",
  "Lunatone",
  "Lurantis",
  "Luxray",
  "Lycanroc Dusk",
  "Lycanroc Midday",
  "Lycanroc Midnight",
  "Machamp",
  "Machoke",
  "Magcargo",
  "Magmar",
  "Magmortar",
  "Magneton",
  "Magnezone",
  "Malamar",
  "Mamoswine",
  "Mandibuzz",
  "Manectric",
  "Mantine",
  "Maractus",
  "Marowak",
  "Marowak Alola",
  "Marshadow",
  "Marshtomp",
  "Masquerain",
  "Maushold Family Of Four",
  "Meganium",
  "Melmetal",
  "Meloetta Aria",
  "Meowscarada",
  "Meowstic Female",
  "Meowstic Male",
  "Mesprit",
  "Metagross",
  "Metang",
  "Mew",
  "Mewtwo",
  "Mienshao",
  "Mightyena",
  "Milotic",
  "Miltank",
  "Misdreavus",
  "Mismagius",
  "Moltres",
  "Moltres Galar",
  "Morpeko Full Belly",
  "Mr Mime",
  "Mr Mime Galar",
  "Mr Rime",
  "Mudbray",
  "Mudsdale",
  "Muk",
  "Muk Alola",
  "Munchlax",
  "Musharna",
  "Naganadel",
  "Necrozma",
  "Necrozma Dawn",
  "Necrozma Dusk",
  "Nidoking",
  "Nidoqueen",
  "Nihilego",
  "Ninetales",
  "Ninetales Alola",
  "Noctowl",
  "Noivern",
  "Obstagoon",
  "Octillery",
  "Oinkologne Female",
  "Oinkologne Male",
  "Omastar",
  "Oranguru",
  "Orbeetle",
  "Oricorio Baile",
  "Oricorio Pau",
  "Oricorio Pom Pom",
  "Oricorio Sensu",
  "Overqwil",
  "Palkia",
  "Palkia Origin",
  "Palossand",
  "Pangoro",
  "Parasect",
  "Passimian",
  "Pawmot",
  "Pelipper",
  "Perrserker",
  "Pidgeot",
  "Pignite",
  "Piloswine",
  "Pinsir",
  "Politoed",
  "Poliwrath",
  "Polteageist",
  "Porygon Z",
  "Porygon2",
  "Primarina",
  "Primeape",
  "Probopass",
  "Purugly",
  "Pyroar Male",
  "Quagsire",
  "Quaquaval",
  "Qwilfish",
  "Qwilfish Hisui",
  "Raichu",
  "Raichu Alola",
  "Raikou",
  "Rampardos",
  "Rapidash",
  "Rapidash Galar",
  "Raticate Alola",
  "Rayquaza",
  "Regice",
  "Regidrago",
  "Regieleki",
  "Regigigas",
  "Regirock",
  "Registeel",
  "Relicanth",
  "Reshiram",
  "Reuniclus",
  "Revavroom",
  "Rhydon",
  "Rhyperior",
  "Ribombee",
  "Rillaboom",
  "Roserade",
  "Rotom",
  "Rotom Fan",
  "Rotom Frost",
  "Rotom Heat",
  "Rotom Mow",
  "Rotom Wash",
  "Runerigus",
  "Salamence",
  "Salazzle",
  "Samurott",
  "Samurott Hisui",
  "Sandslash",
  "Sandslash Alola",
  "Sawk",
  "Sawsbuck",
  "Sceptile",
  "Scizor",
  "Scolipede",
  "Scrafty",
  "Scyther",
  "Seadra",
  "Seaking",
  "Sealeo",
  "Seismitoad",
  "Serperior",
  "Seviper",
  "Sharpedo",
  "Shaymin Land",
  "Shaymin Sky",
  "Shelgon",
  "Shiftry",
  "Shiinotic",
  "Sigilyph",
  "Simipour",
  "Simisage",
  "Simisear",
  "Sinistcha",
  "Sirfetchd",
  "Skarmory",
  "Skeledirge",
  "Skuntank",
  "Slaking",
  "Sliggoo",
  "Slowbro",
  "Slowbro Galar",
  "Slowking",
  "Slowking Galar",
  "Slurpuff",
  "Sneasel",
  "Sneasel Hisui",
  "Sneasler",
  "Snorlax",
  "Solgaleo",
  "Solrock",
  "Spiritomb",
  "Stakataka",
  "Stantler",
  "Staraptor",
  "Starmie",
  "Steelix",
  "Stonjourner",
  "Stoutland",
  "Stunfisk",
  "Stunfisk Galar",
  "Sudowoodo",
  "Suicune",
  "Sunflora",
  "Swalot",
  "Swampert",
  "Swanna",
  "Sylveon",
  "Talonflame",
  "Tangela",
  "Tangrowth",
  "Tapu Bulu",
  "Tapu Fini",
  "Tapu Koko",
  "Tapu Lele",
  "Tatsugiri Curly",
  "Tatsugiri Droopy",
  "Tatsugiri Stretchy",
  "Tauros",
  "Tauros Paldea Aqua Breed",
  "Tauros Paldea Blaze Breed",
  "Tauros Paldea Combat Breed",
  "Tentacruel",
  "Terrakion",
  "Thievul",
  "Throh",
  "Thundurus Incarnate",
  "Thundurus Therian",
  "Thwackey",
  "Tinkaton",
  "Toedscruel",
  "Togedemaru",
  "Togekiss",
  "Togetic",
  "Torkoal",
  "Tornadus Incarnate",
  "Tornadus Therian",
  "Torterra",
  "Toucannon",
  "Toxapex",
  "Toxicroak",
  "Toxtricity Amped",
  "Trevenant",
  "Tropius",
  "Tsareena",
  "Turtonator",
  "Typhlosion",
  "Typhlosion Hisui",
  "Tyranitar",
  "Tyrantrum",
  "Umbreon",
  "Unfezant",
  "Ursaluna",
  "Ursaring",
  "Urshifu Rapid Strike",
  "Urshifu Single Strike",
  "Uxie",
  "Vanilluxe",
  "Vaporeon",
  "Venomoth",
  "Venusaur",
  "Vespiquen",
  "Victini",
  "Victreebel",
  "Vigoroth",
  "Vikavolt",
  "Vileplume",
  "Virizion",
  "Volbeat",
  "Volcanion",
  "Volcarona",
  "Wailord",
  "Walrein",
  "Weavile",
  "Weezing",
  "Weezing Galar",
  "Whimsicott",
  "Whiscash",
  "Wigglytuff",
  "Wormadam Plant",
  "Wormadam Sandy",
  "Wyrdeer",
  "Xatu",
  "Xerneas",
  "Xurkitree",
  "Yanmega",
  "Yveltal",
  "Zacian",
  "Zacian Crowned",
  "Zamazenta",
  "Zamazenta Crowned",
  "Zangoose",
  "Zapdos",
  "Zapdos Galar",
  "Zarude",
  "Zebstrika",
  "Zekrom",
  "Zoroark",
  "Zoroark Hisui",
  "Zweilous",
  "Zygarde 10",
  "Zygarde 50",
  "Zygarde Complete",
];

export const MASTER_LEAGUE_POKEMON: string[] = [
  "Aerodactyl",
  "Aggron",
  "Alakazam",
  "Ampharos",
  "Annihilape",
  "Arboliva",
  "Arcanine",
  "Arcanine Hisui",
  "Archeops",
  "Armaldo",
  "Armarouge",
  "Articuno",
  "Articuno Galar",
  "Aurorus",
  "Avalugg",
  "Avalugg Hisui",
  "Azelf",
  "Barbaracle",
  "Baxcalibur",
  "Beartic",
  "Bellibolt",
  "Bewear",
  "Bisharp",
  "Blacephalon",
  "Blastoise",
  "Blissey",
  "Bouffalant",
  "Braviary",
  "Braviary Hisui",
  "Buzzwole",
  "Carracosta",
  "Celebi",
  "Celesteela",
  "Centiskorch",
  "Ceruledge",
  "Cetitan",
  "Chandelure",
  "Charizard",
  "Chesnaught",
  "Cinderace",
  "Coalossal",
  "Cobalion",
  "Conkeldurr",
  "Corviknight",
  "Crabominable",
  "Cresselia",
  "Crobat",
  "Cryogonal",
  "Cursola",
  "Darkrai",
  "Darmanitan Galar Standard",
  "Darmanitan Standard",
  "Decidueye",
  "Decidueye Hisui",
  "Delphox",
  "Deoxys Defense",
  "Deoxys Speed",
  "Dhelmise",
  "Dialga",
  "Dialga Origin",
  "Diancie",
  "Dondozo",
  "Donphan",
  "Dragapult",
  "Dragonite",
  "Drampa",
  "Druddigon",
  "Dudunsparce Two Segment",
  "Duraludon",
  "Electivire",
  "Emboar",
  "Empoleon",
  "Enamorus Incarnate",
  "Enamorus Therian",
  "Entei",
  "Escavalier",
  "Espeon",
  "Eternatus",
  "Excadrill",
  "Exeggutor",
  "Exeggutor Alola",
  "Feraligatr",
  "Flareon",
  "Florges",
  "Gallade",
  "Garchomp",
  "Gardevoir",
  "Garganacl",
  "Genesect",
  "Gholdengo",
  "Gigalith",
  "Giratina Altered",
  "Giratina Origin",
  "Glaceon",
  "Glimmora",
  "Gliscor",
  "Gogoat",
  "Golem",
  "Golem Alola",
  "Golisopod",
  "Golurk",
  "Goodra",
  "Gourgeist Large",
  "Gourgeist Super",
  "Grimmsnarl",
  "Groudon",
  "Guzzlord",
  "Gyarados",
  "Hariyama",
  "Haxorus",
  "Heatran",
  "Heracross",
  "Hippowdon",
  "Ho Oh",
  "Hoopa",
  "Hoopa Unbound",
  "Hydrapple",
  "Hydreigon",
  "Incineroar",
  "Jirachi",
  "Jolteon",
  "Kangaskhan",
  "Kartana",
  "Keldeo Ordinary",
  "Keldeo Resolute",
  "Kingambit",
  "Kingdra",
  "Kleavor",
  "Klinklang",
  "Kommo O",
  "Krookodile",
  "Kyogre",
  "Kyurem",
  "Kyurem Black",
  "Kyurem White",
  "Landorus Incarnate",
  "Landorus Therian",
  "Lapras",
  "Latias",
  "Latios",
  "Leafeon",
  "Lickilicky",
  "Lugia",
  "Lunala",
  "Luxray",
  "Machamp",
  "Magmortar",
  "Magnezone",
  "Mamoswine",
  "Marshadow",
  "Melmetal",
  "Meloetta Aria",
  "Mesprit",
  "Metagross",
  "Mew",
  "Mewtwo",
  "Milotic",
  "Miltank",
  "Moltres",
  "Moltres Galar",
  "Mr Rime",
  "Mudsdale",
  "Muk",
  "Muk Alola",
  "Musharna",
  "Naganadel",
  "Necrozma",
  "Necrozma Dawn",
  "Necrozma Dusk",
  "Nihilego",
  "Noivern",
  "Obstagoon",
  "Oinkologne Female",
  "Oinkologne Male",
  "Omastar",
  "Oranguru",
  "Overqwil",
  "Palkia",
  "Palkia Origin",
  "Pangoro",
  "Passimian",
  "Pinsir",
  "Poliwrath",
  "Polteageist",
  "Porygon Z",
  "Porygon2",
  "Primarina",
  "Pyroar Male",
  "Quaquaval",
  "Raikou",
  "Rampardos",
  "Rayquaza",
  "Regice",
  "Regidrago",
  "Regigigas",
  "Regirock",
  "Registeel",
  "Relicanth",
  "Reshiram",
  "Reuniclus",
  "Revavroom",
  "Rhydon",
  "Rhyperior",
  "Rillaboom",
  "Roserade",
  "Salamence",
  "Samurott",
  "Samurott Hisui",
  "Scizor",
  "Seismitoad",
  "Shaymin Land",
  "Shaymin Sky",
  "Sinistcha",
  "Sirfetchd",
  "Skeledirge",
  "Slaking",
  "Slowbro",
  "Slowking",
  "Slowking Galar",
  "Sneasler",
  "Snorlax",
  "Solgaleo",
  "Stakataka",
  "Steelix",
  "Stonjourner",
  "Stoutland",
  "Suicune",
  "Swampert",
  "Sylveon",
  "Tangrowth",
  "Tapu Bulu",
  "Tapu Fini",
  "Tapu Koko",
  "Tapu Lele",
  "Tauros Paldea Aqua Breed",
  "Tauros Paldea Blaze Breed",
  "Tauros Paldea Combat Breed",
  "Tentacruel",
  "Terrakion",
  "Throh",
  "Thundurus Incarnate",
  "Thundurus Therian",
  "Toedscruel",
  "Togekiss",
  "Tornadus Incarnate",
  "Tornadus Therian",
  "Torterra",
  "Tsareena",
  "Typhlosion",
  "Typhlosion Hisui",
  "Tyranitar",
  "Tyrantrum",
  "Umbreon",
  "Ursaluna",
  "Ursaring",
  "Urshifu Rapid Strike",
  "Urshifu Single Strike",
  "Uxie",
  "Vanilluxe",
  "Vaporeon",
  "Venusaur",
  "Victini",
  "Vikavolt",
  "Virizion",
  "Volcanion",
  "Volcarona",
  "Walrein",
  "Weavile",
  "Wyrdeer",
  "Xerneas",
  "Xurkitree",
  "Yanmega",
  "Yveltal",
  "Zacian",
  "Zacian Crowned",
  "Zamazenta",
  "Zamazenta Crowned",
  "Zapdos",
  "Zapdos Galar",
  "Zarude",
  "Zekrom",
  "Zygarde 50",
  "Zygarde Complete",
];

/** Map open league names to their meta Pokemon lists. */
export const LEAGUE_POKEMON: Record<string, string[]> = {
  "Great League": GREAT_LEAGUE_POKEMON,
  "Ultra League": ULTRA_LEAGUE_POKEMON,
  "Master League": MASTER_LEAGUE_POKEMON,
};

/**
 * Returns the filtered Pokemon list for a given league.
 * Falls back to null if the league has no specific list (cup formats).
 */
export function getLeaguePokemon(league: string): string[] | null {
  return LEAGUE_POKEMON[league] ?? null;
}
